name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libcppunit-dev libnetcdf-dev libnetcdf-c++4-dev cmake

    - name: Build unit tests
      working-directory: tst/unittests
      run: |
        mkdir build
        cd build
        cmake ..
        make

    - name: Run unit tests
      working-directory: tst/unittests/build
      run: ./unittests
